baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "forty"


[params.navigation]
    title = "Forty"
    subtitle = "By HTML5 Up"
    menu = "Menu"
    # Optional logo as brand stored in img/
    # logo = "logo.png"

    [[params.navigation.links]]
      name = "Home"
      url = "#"